#!/bin/bash

NAME=$1
CONTEXT=$2
DIST=${3:-lenny}

# create basic vserver
vserver $NAME build -m debootstrap -- -d $DIST -m http://ftp.at.debian.org/debian

# default settings
echo $NAME >/etc/vservers/$NAME/uts/nodename
echo $CONTEXT >/etc/vservers/$NAME/context

# copy in some some defaults
TARGET=/etc/vservers/$NAME/vdir/

cp -av /var/lib/puppet/modules/virtual/build_vserver/skel_$DIST/* $TARGET/etc/

# this is needed so puppet can find the puppetmaster and creates the right
# certificate
grep -v $NAME /etc/hosts > $TARGET/etc/hosts
echo "127.0.0.1 $NAME" >> $TARGET/etc/hosts
mkdir -p $TARGET/var/lib/puppet/modules/dbp
cp /var/lib/puppet/modules/dbp/puppet_current.deb $TARGET/var/lib/puppet/modules/dbp/

# Setup is complete, now do the post-install stuff
vserver $NAME start
# refresh apt's knowledge of repositories, needed especially for repo signing
vserver $NAME exec apt-get update
# best install security updates first, before anything else
vserver $NAME exec apt-get -uy dist-upgrade
# install a few packages needed for facter
vserver $NAME exec apt-get -y install lsb-release iproute
vserver $NAME exec dpkg --install var/lib/puppet/modules/dbp/puppet_current.deb
vserver $NAME exec apt-get -fy install

echo "Please sign now: puppetca --sign $NAME" >&2
